name: Generate YAML Rules

on:
  push:
    paths:
      - 'rule/*.list'
  workflow_dispatch:

jobs:
  generate-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate YAML from LIST files
        run: |
          FILES=("Custom_Direct" "Custom_Proxy" "Steam_CDN")  # 将来可在此添加更多文件名

          for base_name in "${FILES[@]}"; do
            list_file="rule/${base_name}.list"
            domain_yaml_file="rule/${base_name}_Domain.yaml"
            ip_yaml_file="rule/${base_name}_IP.yaml"

            timestamp=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')

            domain_rules=$(grep -E '^(DOMAIN-|DOMAIN-SUFFIX|DOMAIN-KEYWORD)' "$list_file" | sed -E "s/^DOMAIN-SUFFIX,(.+)/  - '+.\1'/" | sed -E "s/^DOMAIN-KEYWORD,(.+)/  - '*\1*'/" | sed -E "s/^DOMAIN,(.+)/  - '\1'/")
            ip_rules=$(grep -E '^(IP-|IP-CIDR)' "$list_file" | sed -E "s/^IP-CIDR,([^,]+).*/  - '\1'/" | sed -E "s/^IP,([^,]+).*/  - '\1'/")

            domain_count=$(echo "$domain_rules" | grep -c '  - ' || true)
            ip_count=$(echo "$ip_rules" | grep -c '  - ' || true)

            # 生成域名类规则
            echo "# Generated from ${list_file}" > "$domain_yaml_file"
            echo "# REPO: https://github.com/Aethersailor/Custom_OpenClash_Rules" >> "$domain_yaml_file"
            echo "# SOURCE: https://github.com/Aethersailor/Custom_OpenClash_Rules/blob/main/${list_file}" >> "$domain_yaml_file"
            echo "# UPDATE: ${timestamp}" >> "$domain_yaml_file"
            echo "# TOTAL: ${domain_count}" >> "$domain_yaml_file"
            echo "" >> "$domain_yaml_file"
            echo "payload:" >> "$domain_yaml_file"
            echo "$domain_rules" >> "$domain_yaml_file"

            # 生成IP类规则
            echo "# Generated from ${list_file}" > "$ip_yaml_file"
            echo "# REPO: https://github.com/Aethersailor/Custom_OpenClash_Rules" >> "$ip_yaml_file"
            echo "# SOURCE: https://github.com/Aethersailor/Custom_OpenClash_Rules/blob/main/${list_file}" >> "$ip_yaml_file"
            echo "# UPDATE: ${timestamp}" >> "$ip_yaml_file"
            echo "# TOTAL: ${ip_count}" >> "$ip_yaml_file"
            echo "" >> "$ip_yaml_file"
            echo "payload:" >> "$ip_yaml_file"
            echo "$ip_rules" >> "$ip_yaml_file"

            # 判断是否有变更
            if [[ -n $(git status --porcelain "$domain_yaml_file" "$ip_yaml_file") ]]; then
              git add "$domain_yaml_file" "$ip_yaml_file"

              short_list_file="$(basename "$list_file")"
              short_domain_yaml_file="$(basename "$domain_yaml_file")"
              short_ip_yaml_file="$(basename "$ip_yaml_file")"

              git commit -m "Generate ${short_domain_yaml_file} and ${short_ip_yaml_file} from ${short_list_file}"
            else
              echo "No changes in ${domain_yaml_file} and ${ip_yaml_file}, skip commit."
            fi
          done

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -n $(git log origin/main..HEAD) ]]; then
            git push origin HEAD:main
          else
            echo "No new commits to push."
          fi
